default_stages: [commit]
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.81.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
        files: ^envs/
      - id: terraform_tflint
        files: ^envs/
      - id: terraform_tfsec
