name: "Terraform CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      matrix:
        env_dir:
          - "envs/stg"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials - staging
        if: ${{ matrix.env_dir == 'envs/stg' }}
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::428485887053:role/terraform-expt-terraform-from-github-actions
          aws-region: ap-northeast-1

      - name: Terraform init
        run: |
          cd ${{ matrix.env_dir }}
          terraform init

      - name: Terraform validate
        run: |
          cd ${{ matrix.env_dir }}
          terraform validate

      - name: Setup tfcmt
        env:
          TFCMT_VERSION: v4.4.2
        run: |
          wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
          tar xzf /tmp/tfcmt.tar.gz -C /tmp
          mv /tmp/tfcmt /usr/local/bin
          tfcmt --version

      - name: Terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ${{ matrix.env_dir }}
          tfcmt -var target:${{ matrix.env_dir }} plan -patch -- terraform plan -no-color
