name: "Terraform CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    strategy:
      matrix:
        env:
          - stg
    defaults:
      run:
        working-directory: envs/${{ matrix.env }}
    environment:
      name: ${{ matrix.env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup tfcmt
        env:
          TFCMT_VERSION: v4.4.2
        run: |
          wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
          tar xzf /tmp/tfcmt.tar.gz -C /tmp
          mv /tmp/tfcmt /usr/local/bin
          tfcmt --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1

      - name: Terraform init
        run: terraform init

      - name: Terraform fmt
        run: |
          cd ../..
          terraform fmt -diff -check -recursive

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt -var target:${{ matrix.env }} plan -patch -- terraform plan -no-color
